name: CI/CD workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: node setup
        uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: react-app-build
          path: ./dist
    
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: node setup
        uses: actions/setup-node@v6
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm ci

      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: react-app-build
          path: dist
      
      - name: Run tests
        run: npm test -- --watchAll=false

      - name: check if build file exists
        run: |
          test -f dist/index.html
          echo "Build file exists"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      AZURE_CONTAINER_REGISTRY: devopshorizonreg
      RESOURCE_GROUP: 1-cc102039-playground-sandbox
      CONTAINER_APP_NAME: devops-horizon-container-app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Download Build Artifact
        uses: actions/download-artifact@v6
        with:
          name: react-build
          path: dist

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}